# -*- coding: utf-8 -*-
"""Repair defects baked into the hand-written source pages (en/ and zh/).

These pages are the clone source for every other locale, so a defect here is
reproduced nine times.  Three classes of damage were found:

1. Double-escaped ampersands -- ``&amp;amp;`` renders as a literal "&amp;" in
   the browser and also defeats dictionary matching (the dictionary stores the
   unescaped form).
2. Price-ladder top row ``1000-+ pcs``: the open-ended tier (max = null) was
   rendered as "min-+", which reads as a typo.
3. A stale FAQ answer that leaked a Python repr
   (``US${'currency': 'USD', 'number': 64.5}-None/pc``).  Rewritten to the
   approved wording so the page reads correctly even before regeneration; the
   generator's FAQ->JSON-LD sync keeps it correct from now on.

`en/` is regenerated by gen_pages.py, which now repairs classes 1-3 on the fly,
so this script is normally a no-op there.  `zh/` is hand-maintained and is *not*
regenerated, which is why the same repr leaks survived in 21 Chinese price
cells -- run with ``--langs zh`` to clean them in place.

Usage
    python scripts/fix_en_templates.py                 # en/ (regenerated source)
    python scripts/fix_en_templates.py --langs zh      # hand-maintained locale
    python scripts/fix_en_templates.py --check         # report only
"""
from __future__ import annotations
import argparse, glob, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def _price(num: str) -> str:
    """Format a captured price the way the generator does.

    ``60.0`` -> ``US$60``, but ``64.5`` keeps its decimal.  Without this the
    regex repairs left "US$60.0" where en/ shows "US$60".
    """
    if '.' in num:
        num = num.rstrip('0').rstrip('.')
    return 'US$' + num


RULES = (
    ('double-escaped ampersand', re.compile(r'&amp;amp;'), '&amp;'),
    ('open-ended price tier', re.compile(r'(<td>\d+)&ndash;\+ pcs'), r'\1+ pcs'),
    ('open-ended price tier (literal)', re.compile(r'(<td>\d+)\u2013\+ pcs'), r'\1+ pcs'),
    ('python repr in FAQ answer',
     re.compile(r"Indicative FOB price is US\$\{[^}]*\}[^<]*?tiered by order quantity\."),
     'FOB pricing depends on order quantity and configuration \u2014 '
     'contact us for a quotation.'),
    # compare tables and the product-grid price badge on the hand-written OEM
    # landing pages were rendered straight from Python dicts
    ('python repr in compare price',
     re.compile(r"US\$\{'currency': 'USD', 'number': ([\d.]+)\}"
                r"\u2013\{'currency': 'USD', 'number': [\d.]+\}"),
     lambda m: _price(m.group(1))),
    ('python repr in grid price badge',
     re.compile(r"\$\{'currency': 'USD', 'number': ([\d.]+)\}"
                r"-\$\{'currency': 'USD', 'number': [\d.]+\}"),
     lambda m: _price(m.group(1))),
    # the same FAQ leak on the hand-maintained Chinese pages.  One pattern
    # covers both copies: the visible <p> carries HTML-escaped quotes
    # (&#x27;) while the FAQPage JSON-LD block carries them raw.
    ('python repr in zh FAQ answer',
     re.compile(r'参考 FOB 价 US\$\{.{0,120}?，按数量阶梯浮动。'),
     'FOB 价格取决于订单数量与配置，请联系我们获取报价。'),
    # a stray "US$60.0" left behind wherever a price was written by hand
    ('redundant decimal on a whole-dollar price',
     re.compile(r'US\$(\d+)\.0+(?!\d)'),
     r'US$\1'),
)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--langs', default='en',
                    help='comma-separated locale trees to sweep (default: en)')
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args()

    totals = {name: 0 for name, _, _ in RULES}
    touched = 0
    n_files = 0

    for lang in [l for l in args.langs.split(',') if l]:
        files = sorted(glob.glob(os.path.join(ROOT, lang, '**', '*.html'), recursive=True))
        n_files += len(files)
        print(f'--- {lang}: {len(files)} files ---')
        for fp in files:
            h = open(fp, encoding='utf-8').read()
            out, hits = h, 0
            for name, pat, repl in RULES:
                out, n = pat.subn(repl, out)
                totals[name] += n
                hits += n
            if hits:
                touched += 1
                rel = os.path.relpath(fp, ROOT).replace('\\', '/')
                print(f'  {rel}: {hits} fix(es)')
                if not args.check:
                    with open(fp, 'w', encoding='utf-8') as f:
                        f.write(out)

    print(f'\nscanned {n_files} files, {touched} affected'
          + (' (check only, nothing written)' if args.check else ''))
    for name, n in totals.items():
        print(f'  {name:<34} {n}')
    if not args.check and touched == 0:
        print('  (nothing to do - already clean)')


if __name__ == '__main__':
    main()
